language: android
jdk: oraclejdk8
dist: trusty

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - sys-img-armeabi-v7a-android-24
    - sys-img-armeabi-v7a-android-21

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - sdkmanager --list
  - android list targets
#  - echo no | android create avd --force -n test -t android-28
#  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script:
  - "./gradlew clean connectedCheck"

env:
  global:
    - secure: k0NsdNv78/wIoPFeB2EiJFBiwhh0q1os5edw5TttiKYEyYuvhil3M/sN6J/2IfH2VouObUpeq1rcSvc02i4xpImX0gLhJyZ2WsA9j5YyjXyvIUwMoBgK0TW7o84E1dQNY4xG80oeKUshw5fMepjJvFSuFXJjmolxJYcKZjEKQ/rp4kDj7Ibc8GyLyWjll9yBdmJHCZ1lfdzV5dJ2vsATQdrNP93F8KzMxIT/Y4MsNfK9Wb9CJ/X5oenRpWi6gl1QeipAUBERsD1HoBciG9pmSyRJkwWpO3Ypte5gReap/ECZrtvtlO6rfTtAj5zhrHonIvDZE3SWnFyzNfZuQQwLVMNmkUEwBy/2O+5UPQdY19gbFpyfNj/iwc7N4no+x8MyZ/Pf0+nY38DCiFiRX+OOWKarcxhGFgfgHy2sYbM/ygxKIkGeNC4cyBnUt+gMO/iZpO0WXASsPWIeflHCFZiSD7WUazdfjjNr6vtRrxl+XfdAqs4rEAMV8kwEPFZQih5w4yeNSFUF5cCNBIbAeHDZqYfXnJ8tyWyC7cti7Ufc0hGk2QT/XbYuPkrpOrEYadPLUQV78AaS0DKi9D7vvqZZDNye1XZL7C3jfuuLdhBMeav9jTv0XfkJ2Cy/PjP5mXyeicEpsaYBFsOH0Sz44ZBF3s7+NucZfnKbIkwb91Bg12I=
    - secure: l2Q2Ql23Pi/WhwE4SHLGa5WBDSs3qBKc7NB1jUvMazYGv8PXRcXy2VKJquOZibT7fqUo1DS2k1mFAqa9viXGhMM/0TnPZuK6gQ86vWEZWGjoADcp8jQlKSxM0FsFWKtwkan7oS0sIllMpyo9Dy6b8CT87lk8ybTZhYaYcxNKQAaZqeXlAP43c/DyHz15ETR6ApXHNrHUFXcVNzz1owvSR+xRgJ1mRG3xtH/0Udug1J6X6AV2oD3ySmz8JNP7F7b+pThZThGLh6plqr4kN9dD1zx3i1LO74CSbrVCwvzg2gMhQzECWKjsGrK4XsOgsJataw0gaj3+n6xPzXmb5A86yX22FfpTsEKZTvUrZ6vgjYM/r5FzqUv2k88oMCN+acwQyzOJD5lH6gexPiGwJwQ5zyhi3soOcFvr+zTUOLXRRU0Ru/apP21TtJjbMhsnVHq+9p9sAgZCU3MTAqnw2O6P3nC9X0cQ5y+mwXFHUmKHbTDNsmC24+Q0inpVVlbSMH//60GTtoYPxRyyObM20Ca1nJD/3Y0Z0iHB5+tGo1agenr2i/oF09X7fHz6n91K4UT9Q3YiSOcILDbYS2SJISRffsXDn4MdgmKI4HcwuWqQmVavzrdMkY/nd1AdC7tMXd72lVl1qqCVofl9Wt6BzGjIWGKETaBGNfqNVGo92ccYCxU=
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=26.0.1
    - ANDROID_ABI=armeabi-v7a
    - EMULATOR_API_LEVEL=24
    - ANDROID_TAG=google_apis


before_install:
  - echo "Will need to figure out how to test Android properly"

